import {
  Accessibility,
  Armchair,
  Bath,
  BatteryCharging,
  BedDouble,
  Cctv,
  Check,
  CookingPot,
  Cookie,
  Cross,
  DoorOpen,
  FireExtinguisher,
  Gauge,
  GlassWater,
  IdCard,
  Lamp,
  Layers,
  Luggage,
  MapPin,
  Mic,
  MoveHorizontal,
  Music,
  PanelsTopLeft,
  PlugZap,
  Refrigerator,
  ShieldCheck,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Tv,
  Usb,
  UserRound,
  UtensilsCrossed,
  Wifi,
} from "lucide-react";
import { getAmenity } from "@/lib/constants/amenities";

// Explicit map (not `import *`) so only these icons are bundled.
const ICONS = {
  Accessibility,
  Armchair,
  Bath,
  BatteryCharging,
  BedDouble,
  Cctv,
  CookingPot,
  Cookie,
  Cross,
  DoorOpen,
  FireExtinguisher,
  Gauge,
  GlassWater,
  IdCard,
  Lamp,
  Layers,
  Luggage,
  MapPin,
  Mic,
  MoveHorizontal,
  Music,
  PanelsTopLeft,
  PlugZap,
  Refrigerator,
  ShieldCheck,
  Snowflake,
  Sofa,
  Sparkles,
  SprayCan,
  Tv,
  Usb,
  UserRound,
  UtensilsCrossed,
  Wifi,
};

export default function AmenityIcon({ id, size = 16 }) {
  const Icon = ICONS[getAmenity(id)?.icon] ?? Check;
  return <Icon size={size} aria-hidden="true" strokeWidth={1.9} />;
}
